"""init

Revision ID: 33622c8f7158
Revises: None
Create Date: 2014-12-19 00:21:07.693765

"""

# revision identifiers, used by Alembic.
revision = '33622c8f7158'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.UTCDateTime(), nullable=True),
    sa.Column('updated_at', sa.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    ### end Alembic commands ###
